const Icons = ["https://res.cloudinary.com/dwzhz9qkm/image/upload/nzby5lmlwzlpftbqu7zg",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/tedfn7epzvb6gbilqxxm",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/zughqcuiuwlkcrwu85b1",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/tdttcqqbptusdfiom3u6",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/cd2ryshvtmcrqqlgonzs",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/sf5z93ytgson8oeipn15",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/cddd2ljglycickii9hpb",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/ofyc6de4cvqjqmbqdwfr",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/uoxc0k7bn9ean4fpwli1",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/k0kjwcktoybfeknkmcyp",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/zuq8xnleh8odguv450zw",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/bs87tgm7qkgiec7zqtuz",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/vkjd4yc2m4tkvueg7aaw",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/rezaugvzdngvfosxkf0j",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/zsuytt0ktvptq4hq1vca",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/l3163dvdlxpme1e7xr5y",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/oc3hstfcmym7cqqwoqm1",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/u0mgj3wyfjw11fuoqtip",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/lrezokzaasacjftbkcls",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/ez4chniyjjcpubfhxtwv",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/hp55uxwm9wdsfqg8bwak",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/kmejgnfitdgtyp78gbja",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/xrug4nd2nix0kvlmq8y7",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/shxoaxbzqzkjh8ndmyge",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/cmtwboqubrijkolbsabq",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/dkqmyzwi0xzcsxuvzb31",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/nkmqy4gufolmcsrivnzn",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/lian3wpkkcds2wew2hoi",
    "https://res.cloudinary.com/dwzhz9qkm/image/upload/k3qj1uu2r0obgff47cdi"];

export default Icons;