spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 568994842976-5i56j833sp6eq0tv6298hnui5t2mj1g5.apps.googleusercontent.com
            client-secret: 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
  mail:
    host: smtp.gmail.com
    port: 587
    username: voviettruong141003@gmail.com
    password: qlkz oxjy dpbi ambp
server: 
    port: 8080
